name: test
on: push
jobs:
  windows-x86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86
  windows-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64
  windows-mingw:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        path: luamake
        repository: actboy168/luamake
        submodules : recursive
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-ninja
    - shell: msys2 {0}
      working-directory: luamake
      run: ./compile/build.sh notest
    - shell: msys2 {0}
      run: ./luamake/luamake
  macos-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64
  macos-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actboy168/setup-luamake@master
    # see actions/runner-images#2187
    - run: luamake -arch arm64 -notest
  linux-x64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actboy168/setup-luamake@master
    - run: luamake
    - run: luamake lua test/glibc-version.lua
  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apt-get update -q -y
            apt-get install -q -y gcc g++ ninja-build
          run: |
            cd luamake
            ./compile/build.sh notest
            cd ..
            ./luamake/luamake
  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apt-get update -q -y
            apt-get install -q -y gcc g++ ninja-build
          run: |
            cd luamake
            ./compile/build.sh notest
            cd ..
            ./luamake/luamake
