require('plugins')
require('options')
require('keybindings')
require('catppuccin-config')
require('treesitter-config')
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
require('dashboard-nvim-config')
require('telescope-config')
require('autopairs-config')
require('whichkey-config')
require('lsp')
vim.cmd("colorscheme catppuccin")
vim.o.termguicolors = true
