#!/bin/sh

#      ___         __              __               __ 
#     / _ | __ __ / /_ ___   ___  / /_ ___ _  ____ / /_
#    / __ |/ // // __// _ \ (_-< / __// _ `/ / __// __/
#   /_/ |_|\_,_/ \__/ \___//___  \__/ \_,_/ /_/   \__/ 
                                                       

# Checks if program is already running
start() {
  [ -z "$(pidof -x $1)" ] && ${2:-$1} &
}

# Autostart programs
start /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
start pasystray 
start xfce4-clipman
start "picom --experimental-backends -b"
start "xrandr --output DVI-D-0 --off --output HDMI-0 --mode 1920x1080 --pos 1024x0 --rotate normal --output DP-0 --mode 1024x768 --pos 0x312 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off"
start "nitrogen --restore"

# Autostart scripts
rclone mount GoogleDrive: ~/GoogleDrive/
